---
- name: ansible file to  print  gatherfacts
  hosts: localhost
  become: yes
  tasks:
    - name: printing  system info ipaddress,memory,ram,os_name
      ansible.builtin.setup:
              filter: ansible_architecture
              filter: ansible_os_family
      register: output
    - ansible.builtin.debug:
            var: output.stdout_lines
  roles:
    - webserver