---
- name: terrafrom install using ansible
  hosts: production
  become: yes
  tasks:
          - name: adding terraform repo
            yum_repository:
                    name: hashicorp
                    description: terraform from repo
                    baseurl: https://rpm.releases.hashicorp.com/RHEL/hashicorp.repo
          - name: 
            yum:
                    name: " * "
                    state: latest
          - name: installing terraform
            yum:
                    name: terraform
                    state: present
