---
- name: docker installation on redhat8 server
  hosts: localhost
  become: yes
  tasks:

          - name: yum update
            yum:
                   name: "*"
                   state: latest
          - name: install yum utills
            shell: yum install yum-utils -y
            #yum:
            #       name: yum-utils
            #       state: latest
          - name: add repo from repo
            yum_repository:
                    name: docker
                    description: repofor docker
                    baseurl: https://download.docker.com/linux/centos/8/x86_64/stable/repodata/repomd.xml
                    gpgcheck: no
          - name: installing  docker components
            shell: yum install docker-ce docker-ce-cli containerd.io docker-compose-plugin
